<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['samba_directory_app_description'] = 'The Samba Directory app provides the necessary tools for users, groups, accounts and other directory services.';
$lang['samba_directory_app_name'] = 'Samba Каталог';
$lang['samba_directory_initialize_directory'] = 'Инициализировать каталог';
$lang['samba_directory_password_must_be_7_or_more_characters'] = 'Пароль должен быть 7 или более символов.';
$lang['samba_directory_samba_directory_driver'] = 'Samba Directory Driver';
$lang['samba_directory_samba_directory_driver_description'] = 'Драйвер Samba для служб каталогов';
$lang['samba_directory_username_only'] = 'Username Only';
$lang['samba_directory_with_domain'] = 'With Domain';
