<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['samba_directory_app_description'] = 'The Samba Directory app provides the necessary tools for users, groups, accounts and other directory services.';
$lang['samba_directory_app_name'] = 'Usługa katalogowa Samba';
$lang['samba_directory_initialize_directory'] = 'Inicjacja usługi katalogowej';
$lang['samba_directory_password_must_be_7_or_more_characters'] = 'Hasło musi składać się przynajmniej z 7 znaków.';
$lang['samba_directory_samba_directory_driver'] = 'Sterownik usługi katalogowej Samba';
$lang['samba_directory_samba_directory_driver_description'] = 'Sterownik samba dla usług katalogowych';
$lang['samba_directory_username_only'] = 'Tylko nazwa użytkownika';
$lang['samba_directory_with_domain'] = 'z domeną';
